Repository Financial-Times/o-brand, pull requests merged in 2021-02, with the labels that each got.

#85 major beta: origami component specification v2
  .eslintrc.cjs
  .github/workflows/npm-audit-fix.yml
  .github/workflows/release-origami-component.yml
  .github/workflows/test-origami-component.yml
  .remarkrc.cjs
  .stylelintignore
  .stylelintrc.cjs
  MIGRATION.md
  README.md
  package-lock.json
  package.json
Labels: component, release:beta, release:major

#92 Use latest version of origami-release
  .github/workflows/automatic-tag-and-release.yml
Labels: component

#93 use latest version of origami-ci-tools
  package-lock.json
  package.json
Labels: component, release:beta, release:major

#95 Allow non-whitelabel brands to be customised.
  README.md
  scss/_mixins.scss
  scss/_variables.scss
  test/scss/_mixins.test.scss
Labels: component, release:minor

#101 simplify our dependabot auto-merge system
  .github/workflows/auto-approve.yml
  .github/workflows/automerge.yml
Labels: component
